---
abstract: unknown
author:
  - 'shootnix <shootnix@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Dumper-Store
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 0
  perl: 5.010
resources:
  repository: https://github.com/shootnix/data-dumper-store
version: 1.00
